[2025-01-26T18:44:06.686+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T18:44:06.695+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api scheduled__2025-01-25T00:00:00+00:00 [queued]>
[2025-01-26T18:44:06.699+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api scheduled__2025-01-25T00:00:00+00:00 [queued]>
[2025-01-26T18:44:06.699+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-26T18:44:06.707+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api> on 2025-01-25 00:00:00+00:00
[2025-01-26T18:44:06.713+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=120) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T18:44:06.715+0000] {standard_task_runner.py:72} INFO - Started process 121 to run task
[2025-01-26T18:44:06.715+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'simulative_example_basic_dag', 'read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api', 'scheduled__2025-01-25T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/simulative_example_basic_dag.py', '--cfg-path', '/tmp/tmpbdj86b3w']
[2025-01-26T18:44:06.716+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api
[2025-01-26T18:44:06.991+0000] {task_command.py:467} INFO - Running <TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api scheduled__2025-01-25T00:00:00+00:00 [running]> on host 3cfc25a6c20c
[2025-01-26T18:44:07.037+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulative_example_basic_dag' AIRFLOW_CTX_TASK_ID='read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-25T00:00:00+00:00'
[2025-01-26T18:44:07.037+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T18:44:07.038+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T18:44:07.038+0000] {logging_mixin.py:190} INFO - Current task name:read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api state:running start_date:2025-01-26 18:44:06.695816+00:00
[2025-01-26T18:44:07.038+0000] {logging_mixin.py:190} INFO - Dag name:simulative_example_basic_dag and current dag run status:running
[2025-01-26T18:44:07.039+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T18:44:07.061+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulative_example_basic_dag.py", line 25, in read_data_from_faker_api
    faker_api_conn = BaseHook.get_connection("faker")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `faker` isn't defined
[2025-01-26T18:44:07.067+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-26T18:44:07.068+0000] {logging_mixin.py:190} INFO - Task start:2025-01-26 18:44:06.695816+00:00 end:2025-01-26 18:44:07.067341+00:00 duration:0.371525
[2025-01-26T18:44:07.068+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api> dag:<DAG: simulative_example_basic_dag> dagrun:<DagRun simulative_example_basic_dag @ 2025-01-25 00:00:00+00:00: scheduled__2025-01-25T00:00:00+00:00, state:running, queued_at: 2025-01-26 18:44:04.587135+00:00. externally triggered: False>
[2025-01-26T18:44:07.068+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `faker` isn't defined
[2025-01-26T18:44:07.068+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=simulative_example_basic_dag, task_id=read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api, run_id=scheduled__2025-01-25T00:00:00+00:00, execution_date=20250125T000000, start_date=20250126T184406, end_date=20250126T184407
[2025-01-26T18:44:07.078+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T18:44:07.078+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api (The conn_id `faker` isn't defined; 121)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulative_example_basic_dag.py", line 25, in read_data_from_faker_api
    faker_api_conn = BaseHook.get_connection("faker")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `faker` isn't defined
[2025-01-26T18:44:07.105+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-26T18:44:07.252+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T18:44:07.254+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-26T18:54:27.698+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T18:54:27.708+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api scheduled__2025-01-25T00:00:00+00:00 [queued]>
[2025-01-26T18:54:27.713+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api scheduled__2025-01-25T00:00:00+00:00 [queued]>
[2025-01-26T18:54:27.713+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-26T18:54:27.719+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api> on 2025-01-25 00:00:00+00:00
[2025-01-26T18:54:27.724+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=88) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T18:54:27.725+0000] {standard_task_runner.py:72} INFO - Started process 89 to run task
[2025-01-26T18:54:27.725+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'simulative_example_basic_dag', 'read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api', 'scheduled__2025-01-25T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/simulative_example_basic_dag.py', '--cfg-path', '/tmp/tmpk1ma223x']
[2025-01-26T18:54:27.726+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api
[2025-01-26T18:54:28.010+0000] {task_command.py:467} INFO - Running <TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api scheduled__2025-01-25T00:00:00+00:00 [running]> on host b82bd748d7ce
[2025-01-26T18:54:28.063+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulative_example_basic_dag' AIRFLOW_CTX_TASK_ID='read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-25T00:00:00+00:00'
[2025-01-26T18:54:28.064+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T18:54:28.064+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T18:54:28.064+0000] {logging_mixin.py:190} INFO - Current task name:read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api state:running start_date:2025-01-26 18:54:27.709346+00:00
[2025-01-26T18:54:28.064+0000] {logging_mixin.py:190} INFO - Dag name:simulative_example_basic_dag and current dag run status:running
[2025-01-26T18:54:28.065+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T18:54:28.066+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-26T18:54:28.067+0000] {base.py:84} INFO - Retrieving connection 'faker'
[2025-01-26T18:54:28.103+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-26T18:54:28.108+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T18:54:28.109+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=simulative_example_basic_dag, task_id=read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api, run_id=scheduled__2025-01-25T00:00:00+00:00, execution_date=20250125T000000, start_date=20250126T185427, end_date=20250126T185428
[2025-01-26T18:54:28.113+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-26T18:54:28.114+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-26T18:54:28.114+0000] {logging_mixin.py:190} INFO - Dag name:simulative_example_basic_dag queued_at:2025-01-26 18:54:26.213542+00:00
[2025-01-26T18:54:28.114+0000] {logging_mixin.py:190} INFO - Task hostname:b82bd748d7ce operator:_PythonDecoratedOperator
[2025-01-26T18:54:28.160+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T18:54:28.291+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T18:54:28.293+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
