[2025-01-26T18:42:25.910+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T18:42:25.997+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api manual__2025-01-26T18:42:17.562414+00:00 [queued]>
[2025-01-26T18:42:26.020+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api manual__2025-01-26T18:42:17.562414+00:00 [queued]>
[2025-01-26T18:42:26.023+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-26T18:42:26.072+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api> on 2025-01-26 18:42:17.562414+00:00
[2025-01-26T18:42:26.136+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T18:42:26.174+0000] {standard_task_runner.py:72} INFO - Started process 93 to run task
[2025-01-26T18:42:26.165+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'simulative_example_basic_dag', 'read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api', 'manual__2025-01-26T18:42:17.562414+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/simulative_example_basic_dag.py', '--cfg-path', '/tmp/tmpi7gt9hr2']
[2025-01-26T18:42:26.183+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api
[2025-01-26T18:42:26.610+0000] {task_command.py:467} INFO - Running <TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api manual__2025-01-26T18:42:17.562414+00:00 [running]> on host 3cfc25a6c20c
[2025-01-26T18:42:26.981+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulative_example_basic_dag' AIRFLOW_CTX_TASK_ID='read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api' AIRFLOW_CTX_EXECUTION_DATE='2025-01-26T18:42:17.562414+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-26T18:42:17.562414+00:00'
[2025-01-26T18:42:26.990+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T18:42:26.993+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T18:42:26.994+0000] {logging_mixin.py:190} INFO - Current task name:read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api state:running start_date:2025-01-26 18:42:25.998322+00:00
[2025-01-26T18:42:26.995+0000] {logging_mixin.py:190} INFO - Dag name:simulative_example_basic_dag and current dag run status:running
[2025-01-26T18:42:26.998+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T18:42:27.067+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulative_example_basic_dag.py", line 25, in read_data_from_faker_api
    faker_api_conn = BaseHook.get_connection("faker_api")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `faker_api` isn't defined
[2025-01-26T18:42:27.134+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-26T18:42:27.138+0000] {logging_mixin.py:190} INFO - Task start:2025-01-26 18:42:25.998322+00:00 end:2025-01-26 18:42:27.127650+00:00 duration:1.129328
[2025-01-26T18:42:27.147+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api> dag:<DAG: simulative_example_basic_dag> dagrun:<DagRun simulative_example_basic_dag @ 2025-01-26 18:42:17.562414+00:00: manual__2025-01-26T18:42:17.562414+00:00, state:running, queued_at: 2025-01-26 18:42:17.583059+00:00. externally triggered: True>
[2025-01-26T18:42:27.150+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `faker_api` isn't defined
[2025-01-26T18:42:27.154+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=simulative_example_basic_dag, task_id=read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api, run_id=manual__2025-01-26T18:42:17.562414+00:00, execution_date=20250126T184217, start_date=20250126T184225, end_date=20250126T184227
[2025-01-26T18:42:27.201+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T18:42:27.203+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task read_data_from_faker_api_and_load_to_pg.read_data_from_faker_api (The conn_id `faker_api` isn't defined; 93)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulative_example_basic_dag.py", line 25, in read_data_from_faker_api
    faker_api_conn = BaseHook.get_connection("faker_api")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `faker_api` isn't defined
[2025-01-26T18:42:27.285+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-26T18:42:27.341+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T18:42:27.346+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
