[2025-01-26T18:44:39.892+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T18:44:39.902+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.load_data_to_pg scheduled__2025-01-25T00:00:00+00:00 [queued]>
[2025-01-26T18:44:39.907+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.load_data_to_pg scheduled__2025-01-25T00:00:00+00:00 [queued]>
[2025-01-26T18:44:39.907+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-26T18:44:39.914+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): read_data_from_faker_api_and_load_to_pg.load_data_to_pg> on 2025-01-25 00:00:00+00:00
[2025-01-26T18:44:39.919+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=130) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T18:44:39.921+0000] {standard_task_runner.py:72} INFO - Started process 131 to run task
[2025-01-26T18:44:39.922+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'simulative_example_basic_dag', 'read_data_from_faker_api_and_load_to_pg.load_data_to_pg', 'scheduled__2025-01-25T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/simulative_example_basic_dag.py', '--cfg-path', '/tmp/tmpef0qkow_']
[2025-01-26T18:44:39.923+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask read_data_from_faker_api_and_load_to_pg.load_data_to_pg
[2025-01-26T18:44:40.212+0000] {task_command.py:467} INFO - Running <TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.load_data_to_pg scheduled__2025-01-25T00:00:00+00:00 [running]> on host 3cfc25a6c20c
[2025-01-26T18:44:40.247+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulative_example_basic_dag' AIRFLOW_CTX_TASK_ID='read_data_from_faker_api_and_load_to_pg.load_data_to_pg' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-25T00:00:00+00:00'
[2025-01-26T18:44:40.247+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T18:44:40.248+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T18:44:40.248+0000] {logging_mixin.py:190} INFO - Current task name:read_data_from_faker_api_and_load_to_pg.load_data_to_pg state:running start_date:2025-01-26 18:44:39.902902+00:00
[2025-01-26T18:44:40.248+0000] {logging_mixin.py:190} INFO - Dag name:simulative_example_basic_dag and current dag run status:running
[2025-01-26T18:44:40.248+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T18:44:40.253+0000] {logging_mixin.py:190} INFO - None
[2025-01-26T18:44:40.262+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulative_example_basic_dag.py", line 45, in load_data_to_pg
    pg_conn = BaseHook.get_connection("postgres")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2025-01-26T18:44:40.265+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-26T18:44:40.265+0000] {logging_mixin.py:190} INFO - Task start:2025-01-26 18:44:39.902902+00:00 end:2025-01-26 18:44:40.265467+00:00 duration:0.362565
[2025-01-26T18:44:40.266+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): read_data_from_faker_api_and_load_to_pg.load_data_to_pg> dag:<DAG: simulative_example_basic_dag> dagrun:<DagRun simulative_example_basic_dag @ 2025-01-25 00:00:00+00:00: scheduled__2025-01-25T00:00:00+00:00, state:running, queued_at: 2025-01-26 18:44:37.565499+00:00. externally triggered: False>
[2025-01-26T18:44:40.266+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `postgres` isn't defined
[2025-01-26T18:44:40.266+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=simulative_example_basic_dag, task_id=read_data_from_faker_api_and_load_to_pg.load_data_to_pg, run_id=scheduled__2025-01-25T00:00:00+00:00, execution_date=20250125T000000, start_date=20250126T184439, end_date=20250126T184440
[2025-01-26T18:44:40.270+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T18:44:40.271+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task read_data_from_faker_api_and_load_to_pg.load_data_to_pg (The conn_id `postgres` isn't defined; 131)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulative_example_basic_dag.py", line 45, in load_data_to_pg
    pg_conn = BaseHook.get_connection("postgres")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2025-01-26T18:44:40.318+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-26T18:44:40.444+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T18:44:40.446+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-26T18:56:51.544+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T18:56:51.552+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.load_data_to_pg scheduled__2025-01-25T00:00:00+00:00 [queued]>
[2025-01-26T18:56:51.556+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.load_data_to_pg scheduled__2025-01-25T00:00:00+00:00 [queued]>
[2025-01-26T18:56:51.556+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-26T18:56:51.561+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): read_data_from_faker_api_and_load_to_pg.load_data_to_pg> on 2025-01-25 00:00:00+00:00
[2025-01-26T18:56:51.564+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=132) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T18:56:51.565+0000] {standard_task_runner.py:72} INFO - Started process 133 to run task
[2025-01-26T18:56:51.566+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'simulative_example_basic_dag', 'read_data_from_faker_api_and_load_to_pg.load_data_to_pg', 'scheduled__2025-01-25T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/simulative_example_basic_dag.py', '--cfg-path', '/tmp/tmpl4betqvg']
[2025-01-26T18:56:51.567+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask read_data_from_faker_api_and_load_to_pg.load_data_to_pg
[2025-01-26T18:56:51.727+0000] {task_command.py:467} INFO - Running <TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.load_data_to_pg scheduled__2025-01-25T00:00:00+00:00 [running]> on host b82bd748d7ce
[2025-01-26T18:56:51.789+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulative_example_basic_dag' AIRFLOW_CTX_TASK_ID='read_data_from_faker_api_and_load_to_pg.load_data_to_pg' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-25T00:00:00+00:00'
[2025-01-26T18:56:51.789+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T18:56:51.790+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T18:56:51.790+0000] {logging_mixin.py:190} INFO - Current task name:read_data_from_faker_api_and_load_to_pg.load_data_to_pg state:running start_date:2025-01-26 18:56:51.552994+00:00
[2025-01-26T18:56:51.790+0000] {logging_mixin.py:190} INFO - Dag name:simulative_example_basic_dag and current dag run status:running
[2025-01-26T18:56:51.790+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T18:56:51.814+0000] {logging_mixin.py:190} INFO - None
[2025-01-26T18:56:51.816+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-26T18:56:51.818+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-01-26T18:56:51.819+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulative_example_basic_dag.py", line 51, in load_data_to_pg
    data.to_sql("person", pg_engine, if_exists="append", index=False)
    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'to_sql'
[2025-01-26T18:56:51.827+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-26T18:56:51.827+0000] {logging_mixin.py:190} INFO - Task start:2025-01-26 18:56:51.552994+00:00 end:2025-01-26 18:56:51.827487+00:00 duration:0.274493
[2025-01-26T18:56:51.828+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): read_data_from_faker_api_and_load_to_pg.load_data_to_pg> dag:<DAG: simulative_example_basic_dag> dagrun:<DagRun simulative_example_basic_dag @ 2025-01-25 00:00:00+00:00: scheduled__2025-01-25T00:00:00+00:00, state:running, queued_at: 2025-01-26 18:56:46.180806+00:00. externally triggered: False>
[2025-01-26T18:56:51.828+0000] {logging_mixin.py:190} INFO - Failure caused by 'NoneType' object has no attribute 'to_sql'
[2025-01-26T18:56:51.828+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=simulative_example_basic_dag, task_id=read_data_from_faker_api_and_load_to_pg.load_data_to_pg, run_id=scheduled__2025-01-25T00:00:00+00:00, execution_date=20250125T000000, start_date=20250126T185651, end_date=20250126T185651
[2025-01-26T18:56:51.834+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T18:56:51.834+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task read_data_from_faker_api_and_load_to_pg.load_data_to_pg ('NoneType' object has no attribute 'to_sql'; 133)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulative_example_basic_dag.py", line 51, in load_data_to_pg
    data.to_sql("person", pg_engine, if_exists="append", index=False)
    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'to_sql'
[2025-01-26T18:56:51.874+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-26T18:56:52.141+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T18:56:52.144+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
